# Generated by Django 5.1.1 on 2024-09-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combinationskin',
            name='facewash_image',
        ),
        migrations.RemoveField(
            model_name='combinationskin',
            name='moisturizer_image',
        ),
        migrations.RemoveField(
            model_name='combinationskin',
            name='serum_image',
        ),
        migrations.RemoveField(
            model_name='combinationskin',
            name='sunscreen_image',
        ),
        migrations.RemoveField(
            model_name='dryskin',
            name='facewash_image',
        ),
        migrations.RemoveField(
            model_name='dryskin',
            name='moisturizer_image',
        ),
        migrations.RemoveField(
            model_name='dryskin',
            name='serum_image',
        ),
        migrations.RemoveField(
            model_name='dryskin',
            name='sunscreen_image',
        ),
        migrations.RemoveField(
            model_name='normalskin',
            name='facewash_image',
        ),
        migrations.RemoveField(
            model_name='normalskin',
            name='moisturizer_image',
        ),
        migrations.RemoveField(
            model_name='normalskin',
            name='serum_image',
        ),
        migrations.RemoveField(
            model_name='normalskin',
            name='sunscreen_image',
        ),
        migrations.RemoveField(
            model_name='oilyskin',
            name='facewash_image',
        ),
        migrations.RemoveField(
            model_name='oilyskin',
            name='moisturizer_image',
        ),
        migrations.RemoveField(
            model_name='oilyskin',
            name='serum_image',
        ),
        migrations.RemoveField(
            model_name='oilyskin',
            name='sunscreen_image',
        ),
    ]
