# Generated by Django 5.0.7 on 2024-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0002_remove_combinationskin_facewash_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationskin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skincare_images/'),
        ),
        migrations.AddField(
            model_name='dryskin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skincare_images/'),
        ),
        migrations.AddField(
            model_name='normalskin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skincare_images/'),
        ),
        migrations.AddField(
            model_name='oilyskin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skincare_images/'),
        ),
    ]
