# Generated by Django 5.0.7 on 2024-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0003_combinationskin_image_dryskin_image_normalskin_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combinationskin',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dryskin',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='normalskin',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='oilyskin',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
