# Generated by Django 5.0.7 on 2024-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0005_rename_image_combinationskin_face_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image_url', models.URLField(max_length=500)),
                ('purchase_link', models.URLField(max_length=500)),
            ],
        ),
    ]
