# Generated by Django 5.0.7 on 2024-10-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0007_body_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationskin',
            name='face_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='combinationskin',
            name='moisturizer_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='combinationskin',
            name='serum_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='combinationskin',
            name='sunscreen_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='dryskin',
            name='face_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='dryskin',
            name='moisturizer_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='dryskin',
            name='serum_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='dryskin',
            name='sunscreen_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='normalskin',
            name='face_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='normalskin',
            name='moisturizer_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='normalskin',
            name='serum_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='normalskin',
            name='sunscreen_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='oilyskin',
            name='face_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='oilyskin',
            name='moisturizer_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='oilyskin',
            name='serum_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
        migrations.AddField(
            model_name='oilyskin',
            name='sunscreen_link',
            field=models.URLField(default='default_value', max_length=500),
        ),
    ]
