# Generated by Django 5.0.7 on 2024-10-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0008_combinationskin_face_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='body_Recommendations',
        ),
    ]
