# Generated by Django 5.0.7 on 2024-10-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinapp', '0010_healthcarerecommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='body_Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image_url', models.URLField(max_length=500)),
                ('purchase_link', models.URLField(max_length=500)),
            ],
        ),
    ]
